name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Download blosc jar
      run: |
        wget https://static.webknossos.org/misc/blosc-java-0.1-1.21.4-SNAPSHOT.jar
        mkdir -p ../blosc-java/target
        mv *.jar ../blosc-java/target

    - name: Build
      run: mvn -B package --file pom.xml

    - name: Test
      run: mvn test
