name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Download blosc jar
      run: |
        wget https://github.com/scalableminds/blosc-java/suites/13916752572/artifacts/774573653 -O blosc-jar.zip
        unzip blosc-jar.zip
        mkdir -p ../blosc-java/target
        mv *.jar ../blosc-java/target
        rm blosc-jar.zip

    - name: Build
      run: mvn -B package --file pom.xml

    - name: Test
      run: mvn test
